const express = require('express')
const path = require('path')
const session = require('express-session')
const app = express()
app.set('view engine' ,'ejs')
app.set('views', path.join(__dirname, '../renderer/views'))
app.use(express.static(path.join(__dirname, '../renderer/public')))
app.use(express.urlencoded({extended: false}))
app.use(session({
    secret: 'segredo-super-seguro',
    resave: false,
    saveUninitialized: false,
}))
const authRouter = require('./routers/auth')
const dashboardRouter = require('./routers/dashboard')
const atendimentoRouter = require('./routers/atendimento')
const minhacontaRouter = require('./routers/minhaconta')
const sairRouter = require('./routers/sair') 
const carrinhoRouter = require('./routers/carrinho')
const sobrenosRouter = require('./routers/sobrenos') 
const termosRouter = require('./routers/termos') 
const trocasRouter = require('./routers/trocas') 
const privacidadeRouter = require('./routers/privacidade')
const adminRouter = require('./routers/admin')
app.use('/', authRouter)
app.use('/dashboard', dashboardRouter)
app.use('/atendimento', atendimentoRouter)
app.use('/minhaconta', minhacontaRouter)
app.use('/sair', sairRouter)
app.use('/carrinho', carrinhoRouter)
app.use('/sobrenos', sobrenosRouter)
app.use('/termos', termosRouter)
app.use('/trocas', trocasRouter)
app.use('/privacidade', privacidadeRouter)
app.use('/admin', adminRouter)
app.listen(4040, ()=>{
    console.log('Servidor inicializado em http://localhost:4040')
})